version: '3.8'
services:

  gateway:
    build: gateway
    image: shareit_gateway_image
    container_name: shareit_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - SHAREIT_SERVER_HOST=server
      - SHAREIT_SERVER_PORT=9090
#      - TZ=Europe/Moscow

  server:
    build: server
    image: shareit_server_image
    container_name: shareit_server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DB_NAME=postgres
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=5432
#      - TZ=Europe/Moscow

  db:
    image: postgres:16-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
#      - TZ=Europe/Moscow
